apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-record-topic
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-kafka-instance
spec:
  config:
    retention.ms: 150000
  partitions: 3
  replicas: 3
  topicName: my-record-topic
