{
 "title": "Strimzi Kafka Exporter",
 "description": "Kafka topics and consumer groups",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace",
    "label": "Namespace",
    "query": "query_result(kafka_exporter_build_info)"
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_current_offset{namespace=\"$kubernetes_namespace\"}, consumergroup)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{namespace=\"$kubernetes_namespace\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions at minimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are at their minimum in sync replica count (| ISR | == | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions under minimum ISR",
   "type": "singlestat",
   "description": "Number of partitions which are under their minimum in sync replica count (| ISR | < | min.insync.replicas |).",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_underminisr{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Partitions not on preferred node",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader_is_preferred{topic=~\"$topic\"}<1)"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in per second",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "avg(sum(rate(kafka_topic_partition_current_offset{topic=~\"$topic\"}[7m])) by (topic))",
     "legendFormat": "{{topic}} 7 min. average"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (kafka_log_log_size{namespace=\"$kubernetes_namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"kafka\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Partitions",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{topic=~\"$topic\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Latest Offsets",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=~\"$topic\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Oldest Offsets",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_oldest_offset{topic=~\"$topic\"}) by (partition,topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}