{
 "title": "Kafka Producers",
 "description": "Metrics for monitoring Kafka record producers' performance and statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kafka_producer_buffer_available_bytes{},namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kafka_producer_buffer_available_bytes{namespace=~\"$namespace\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Batch Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Producer record queue time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_max{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} max queue time"
    },
    {
     "expr": "kafka_producer_record_queue_time_avg{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}} avg queue time"
    }
   ]
  },
  {
   "title": "Average record size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_size_avg{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Record send rate (observed over total)",
   "type": "graph",
   "description": "This is calculated from kafka_producer_record_send_total with rating instead of direct usage of kafka_producer_record_send_rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total{namespace=~\"$namespace\", pod=~\"$pod\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Producer Record Send Rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_send_rate{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Producer Available Buffer Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(kafka_producer_buffer_available_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}/kafka_producer_buffer_total_bytes{namespace=~\"$namespace\", pod=~\"$pod\"})*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-process"
    },
    {
     "expr": "system_cpu_usage{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}-system"
    }
   ]
  },
  {
   "title": "Producer Buffer Available Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Producer Waiting Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_waiting_threads{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Producer Record Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_record_error_rate{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total connection count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_connection_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Buffer Pool Wait ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_bufferpool_wait_ratio{namespace=~\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}