apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: quarkusMonitor
  labels:
    monitor: 'true'
    prometheus: k8s
spec:
  namespaceSelector:
    matchNames:
      - kafka-performance-test
  podMetricsEndpoints:
    - interval: 3s
      path: /q/metrics
      port: http
  selector:
    matchLabels:
      monitor: 'true'
