apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafkaMonitor
  labels:
    monitor: 'true'
    prometheus: k8s
spec:
  endpoints:
    - path: /metrics
      port: tcp-prometheus
  namespaceSelector:
    matchNames:
      - kafka-cluster
  selector:
    matchLabels:
      strimzi.io/kind: Kafka
